name: VUnit
on: [push, pull_request]
jobs:
  VUnit_Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: srt32/git-actions@v0.0.3
        with:
          args: git update-index --chmod=+x run.py
      - uses: VUnit/vunit_action@master
        with:
          cmd: python3 ./run.py -x test_result.xml
      - name: Publish VUnit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: test_result.xml
          check_name: VUnit Test Results
          check_run_annotations: all tests, skipped tests
